-- Historical migration placeholder retained for Supabase Preview migration-history alignment.
-- The corresponding migration is already applied on the remote project.
-- The later 20260927115724 migration contains the current non-recursive policy helper.
-- Do not add new schema changes here.
